apiVersion: apps/v1
kind: Deployment
metadata:
  name: fadeev-1
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: fadeev-1
  template:
    metadata:
      labels:
        app: fadeev-1
    spec:
      containers:
      - image: barte1by/k8sphpv1:latest
        name: fadeev
        ports:
        - containerPort: 80